---
title: "p8105_hw6_jh3909"
author: "Jingxuan He(UNI: jh3909),
         Yue Pan (UNI:yp2463 )" 
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
library(tidytext)
library(shiny)
theme_set(theme_bw())
```


```{r, echo=FALSE}
# set.seed(1)
# # How the data was cleaned and shrinked:
# NYC_restaurant_data = read_csv("DOHMH_New_York_City_Restaurant_Inspection_Results.csv.gz", col_types = cols(building = col_character()),
#                            na = c("NA", "N/A")) %>%
#   filter(grade %in% c("A", "B", "C")) %>%
#   mutate(inspection_num = row_number(),
#          boro = str_to_title(boro)) %>%
#   filter(boro !="Missing") %>%
#   select(inspection_num, boro, grade, score, cuisine_description, violation_description, inspection_date)
# NYC_restaurant_data = NYC_restaurant_data[sample(nrow(NYC_restaurant_data,10000),]
# write.csv(NYC_restaurant_data, "NYC_restaurant_data.csv")

# Use the shrinked dataset
NYC_restaurant_data = read_csv("NYC_restaurant_data.csv")

# Sentiment plot
inspection_words = NYC_restaurant_data %>% 
  unnest_tokens(word, violation_description)

data(stop_words)

inspection_words = 
  anti_join(inspection_words, stop_words)

bing_sentiments = get_sentiments("bing")

inspection_sentiments = inspection_words %>% 
  inner_join(., bing_sentiments) %>% 
  count(inspection_num, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% 
  mutate(sentiment = positive - negative) %>% 
  select(inspection_num, sentiment)

inspection_sentiments = 
  right_join(NYC_restaurant_data, inspection_sentiments, 
             by = "inspection_num")
```