---
title: "p8105_hw6_jh3909"
author: "Jingxuan He(UNI: jh3909),
         Yue Pan (UNI: )" 
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: embed
  runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
library(tidytext)
library(shiny)
theme_set(theme_bw())

# Make some noisily increasing data
set.seed(955)
dat <- data.frame(cond = rep(c("A", "B"), each=10),
                  xvar = 1:20 + rnorm(20,sd=3),
                  yvar = 1:20 + rnorm(20,sd=3))
```


```{r, echo=FALSE}
set.seed(1)

NYC_restaurant_data = read_csv("DOHMH_New_York_City_Restaurant_Inspection_Results.csv.gz", col_types = cols(building = col_character()),
                           na = c("NA", "N/A")) %>%
  filter(grade %in% c("A", "B", "C")) %>% 
  mutate(inspection_num = row_number(),
         boro = str_to_title(boro)) %>% 
  filter(boro !="Missing") %>% 
  select(inspection_num, boro, grade, score, critical_flag, dba, cuisine_description,   zipcode, violation_description, inspection_date)


# Sentiment plot
inspection_words = NYC_restaurant_data %>% 
  unnest_tokens(word, violation_description)

data(stop_words)

inspection_words = 
  anti_join(inspection_words, stop_words)

bing_sentiments = get_sentiments("bing")

inspection_sentiments = inspection_words %>% 
  inner_join(., bing_sentiments) %>% 
  count(inspection_num, sentiment) %>% 
  spread(sentiment, n, fill = 0) %>% 
  mutate(sentiment = positive - negative) %>% 
  select(inspection_num, sentiment)

inspection_sentiments = 
  right_join(NYC_restaurant_data, inspection_sentiments, 
             by = "inspection_num")
```

geom_point
=======================================================================


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r, echo=FALSE}
# make a box plot; x = cuisine_descirption; y= score
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r, echo=FALSE}
# plot that shows the number of rows for each inspection date
NYC_restaurant_data %>% 
  separate(inspection_date, into=c("year","month","day", sep="-")) %>% 
  mutate(month = month.abb[as.numeric(month)]) %>% 
  select(inspection_num:month) %>% 
  unite(year_month, c(year, month), sep = "-", remove=FALSE) %>% 
  count(year_month) %>% 
  plot_ly(x = ~year_month, y = ~n, type="scatter", mode = "lines") %>% 
  layout(title = "The number of restaurants that were spected for each inspection date", xaxis = list(type="number of restaurants"))

```

### Chart C

```{r, echo=FALSE}
## histrogram of the number of restaurants in each boro
NYC_restaurant_data %>% 
  count(boro) %>% 
  mutate(boro = fct_reorder(boro, n)) %>% 
  plot_ly(y = ~n, color = ~boro, type = "bar") %>%
  layout(xaxis = list(title = "Boro"), yaxis = list(title = "Count"))
```

Shiny Sentiment plot
=======================================================================

Column {.sidebar}
-----------------------------------------------------------------------
```{r, echo=FALSE}
boros = NYC_restaurant_data %>% distinct(boro) %>% pull()

selectInput("boro_choice", label = h3("Select boro"),
            choices = boros, selected = "Manhattan")
```

### Chart D

```{r, echo=FALSE}
renderPlotly({
  inspection_sentiments %>% 
  filter(boro == input$boro_choice) %>% 
  sample_n(400) %>% 
  mutate(inspection_num = factor(inspection_num),
    inspection_num = fct_reorder(inspection_num, sentiment)) %>% 
  ggplot(aes(x = inspection_num, 
             y = sentiment, fill = grade, color = grade)) + 
  geom_bar(stat = "identity") + 
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) +
  scale_fill_viridis(discrete = TRUE) + 
  scale_color_viridis(discrete = TRUE) 
})
```
